name: 28911_test

on:
  push:
    branches:
      - main

jobs:
  check-tests:
    name: Check for Test Scripts
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify existence of 'tests' folder
        shell: bash
        run: |
          if [ ! -d "./tests" ]; then
            echo "The 'tests' folder is missing, so tests cannot be executed." > napaka.txt
          elif [ -z "$(ls -A ./tests)" ]; then
            echo "The 'tests' folder is empty — test scripts do not exist." > napaka.txt
          else
            echo "Test scripts are present."
          fi

      - name: Completion Message
        shell: bash
        run: |
          echo "Check completed."

      - name: Upload napaka.txt as artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: check-output
          path: napaka.txt

  run-tests:
    name: Set Up Environment and Run Tests (with matrix)
    needs: [check-tests]
    runs-on: self-hosted

    strategy:
      matrix:
        php-version: [ '7.4', '8.0', '8.1' ]
    steps:
      - name: Download artifact "napaka.txt"
        uses: actions/upload-artifact@v2
        with:
          name: check-output
          path: ./

      - name: Check for errors from the first job
        id: check_error
        run: |
          if [ -f napaka.txt ] && [ -s napaka.txt ]; then
            echo "Test script not properly set up or missing. Contents of napaka.txt:"
            cat napaka.txt
            exit 1
          else
            echo "No errors in napaka.txt. Proceeding with tests."
          fi

      - name: Set up PHP (${{ matrix.php-version }})
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install dependencies (if using Composer)
        run: composer install --no-progress --no-suggest

      - name: Run custom tests
        shell: bash
        run: |
          if [ -f "./tests/test.sh" ]; then
            echo "Running custom tests from tests/test.sh..."
            bash ./tests/test.sh
          else
            echo "No custom test script found! Exiting."
            exit 1
          fi
