name: Test Self-Hosted Runner

on:
  push:
    branches: [main]

jobs:
  hello:
    runs-on: self-hosted
    steps:
      - name: Print Hello
        run: echo "✅ Hello from your self-hosted runner!"
